name: Application One
run-name: SDLC for Application One 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.actor }} with ${{ github.event_name }} event, status is ${{ job.status }}."
      - name: Notify Slack on Build Start
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Build job started for Application One."}' ${{ secrets.SLACK_WEBHOOK_URL }}
      
  sast:
    needs: build
    uses: outofdevops/shared-workflows/.github/workflows/sast.yaml@main
    with:
      run-name: "Static Application Security Testing for Application-One"
  
  provision-infra:
    runs-on: ubuntu-latest
    steps:
      - run: echo "⚙️ Provisioning testing infrastructure for Application One."
      - name: Notify Slack on Provision Infra Start
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Provisioning infrastructure for Application One."}' ${{ secrets.SLACK_WEBHOOK_URL }}

  dockerise:
    needs: build
    uses: outofdevops/application-one/.github/workflows/dockerise.yaml@main
    with:
      image: "application-one"

  end-2-end:
    runs-on: ubuntu-latest
    needs:
      - dockerise
      - provision-infra
    steps:
      - run: echo "⚙️ Running E2E tests"
      - name: Notify Slack on E2E Start
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"End-to-End tests started for Application One."}' ${{ secrets.SLACK_WEBHOOK_URL }}

  promote:
    needs: 
      - end-2-end
      - sast
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ github.token }}"\
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/promote.yaml/dispatches \
            -d '{"ref":"main","inputs":{"path":"/service-one","image-name":"service-one"}}'
      - name: Notify Slack on Promotion Start
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Promotion started for Application One."}' ${{ secrets.SLACK_WEBHOOK_URL }}

  destroy-infra:
    needs: end-2-end
    runs-on: ubuntu-latest
    steps:
      - run: echo "⚙️ Destroying testing infrastructure for Application One."
      - name: Notify Slack on Destroy Infra Start
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Destroying testing infrastructure for Application One."}' ${{ secrets.SLACK_WEBHOOK_URL }}
