name: Application One
run-name: SDLC for Application One 🚀
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.actor }} with ${{ github.event_name }} event, status is ${{ job.status }}."
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          yarn install
        continue-on-error: false

  sast:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Static Analysis
        run: |
          echo "Running Static Application Security Testing (SAST)..."
          # Simula la ejecución de SAST, reemplaza con tu comando real
          echo "SAST completed successfully!"
        continue-on-error: false

  provision-infra:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "⚙️ Provisioning testing infrastructure for Application One."
        continue-on-error: false

  dockerise:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          echo "Building Docker image..."
          docker build -t application-one:latest .
          docker tag application-one:latest ${{ secrets.DOCKER_USERNAME }}/application-one:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/application-one:latest
        continue-on-error: false

  end-2-end:
    runs-on: ubuntu-latest
    needs:
      - dockerise
      - provision-infra
    steps:
      - run: echo "⚙️ Running E2E tests"
        continue-on-error: false

  promote:
    needs: end-2-end
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ github.token }}"\
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/promote.yaml/dispatches \
            -d '{"ref":"main","inputs":{"path":"/service-one","image-name":"service-one"}}'
        continue-on-error: false

  destroy-infra:
    needs: end-2-end
    runs-on: ubuntu-latest
    steps:
      - run: echo "⚙️ Destroying testing infrastructure for Application One."
        continue-on-error: false

  trigger-dependencies:
    needs: promote
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}"\
            https://api.github.com/repos/outofdevops/application-two/actions/workflows/build.yaml/dispatches \
            -d '{"ref":"main","inputs":{"image-name":"service-one"}}'
        continue-on-error: false
