name: Build and Log Monitoring

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn install

    - name: Build with logs
      run: yarn build:log

    - name: Display logs
      run: |
        echo "Displaying build logs..."
        cat ./logs/build.log || echo "No logs found"

    - name: Upload build logs
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: ./logs/build.log
        if-no-files-found: warn
