name: Monitoring and Logs Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Log Environment Variables
        run: |
          echo "Node.js version: $(node -v)"
          echo "Yarn version: $(yarn -v)"
          echo "Environment: ${{ github.event_name }}"
        env:
          CUSTOM_ENV_VAR: 'production'

      - name: Run Tests
        run: yarn test --ci

      - name: Deploy to Docker
        run: |
          docker build -t my-react-app .
          docker run -d -p 3000:3000 my-react-app

      - name: Display Docker Logs
        run: docker logs $(docker ps -q -f ancestor=my-react-app)

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Linter
        run: yarn lint
