name: Monitoring and Logging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Log Monitoring
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Step 4: Build the project
      - name: Build Project
        run: yarn build

      # Step 5: Log monitoring
      - name: Display Logs
        run: |
          echo "Displaying build logs..."
          cat ./logs/build.log || echo "No logs found"
      
      # Step 6: Save logs as artifacts
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: ./logs/build.log
